# Default property values for Field Splitter Processor
default.fieldToSplit=${fieldsplitter.default.fieldToSplit}
default.fieldSplitter=${fieldsplitter.default.fieldSplitter}

# Processor Properties
PROCESSOR_NAME=${project.name}
PROCESSOR_DOMAIN=${project.groupId}
PROCESSOR_VERSION=${project.version}
PROCESSOR_CONTACT=${contact.address}
PROCESSOR_LABEL=Field Splitter
PROCESSOR_DESC=Release ${project.release}: Split a string field with delimited values into individual GeoEvents

# Field Splitter Properties
FIELD_TO_SPLIT_LABEL=Field to Split
FIELD_TO_SPLIT_DESC=Name of the field whose value will be split into individual GeoEvents
FIELD_SPLITTER_LABEL=Delimiter
FIELD_SPLITTER_DESC=Character or String used to split the field value into individual GeoEvents

